#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use DFrame\Application\Command;
use DFrame\Command\Register;

// Kernel
$cli = new Command();

// Load core commands
(new Register())->core($cli);

// Load user commands
$router = __DIR__ . '/app/Router/command.php';
if (file_exists($router)) {
    require $router;
}

$cli->run($argv);
