services:
  dlight-app:
    environment:
      - DOCKER_RUNNING=true
    build: .
    container_name: dlight_backend
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - dlight_network

  dlight-nginx:
    image: nginx:alpine
    container_name: dlight_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker-nginx-config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dlight-app
    networks:
      - dlight_network

networks:
  dlight_network:
    driver: bridge